### ISSUE TITLE
Highlight which track is playing

### ISSUE THREAD

**Issue by jackdesert** [fabiofalci/sconsify#48]
Highlight works great when using arrow keys to select a song to play.

If that highlighting could move to the next song when the next song plays, that would be *so helpful*

**Comment by fabiofalci** [comment]
That could be tricky using colours as gocui (https://github.com/jroimartin/gocui) just allow you to use few colours (foreground, background) and the user may be navigating and then sconsify would interfere in this navigation.

One way to go is to use chars instead of colours, like:

```
1. Daft Punk - Derezze
2. <<Daft Punk - The Son of Flynn>>
3. Daft Punk - TRON Legacy (End Titles)
```
 Embracing the track with something like `<<...>>`, `[...]`, `(...)`, `->...<-`, etc.

**Comment by fabiofalci** [comment]
https://github.com/fabiofalci/sconsify/pull/53 fixed
