### ISSUE TITLE
Save API key?

### ISSUE THREAD

**Issue by chrislovessushi** [fabiofalci/sconsify#69]
Is there a way to save this so I don't have to enter it each time I start the application?

**Comment by fabiofalci** [comment]
Not at the moment.

Actually, the token is cached but only for 1 hour, which is the time the token is valid.
So if you quit/enter again in 1 hour, it won't be necessary to enter the token again.

If you don't quit the application in 1 hour, sconsify will still work because it only uses the token to load the playlists, at the very beginning.

Spotify can issue long tokens - using a refresh token. That would be ideal however it needs a server to handle the process.

Maybe next versions of sconsify can include that, having a server to handle these tokens.

**Comment by fabiofalci** [comment]
Closing the issue.
Will plan the server auth in the next releases.
